fernanda_project_acronym = ['acad', 'apio', 'cdps', 'ctas', 'fepw', 'parc', 'rtto', 'tbgr', 'trfo', 'atmo', 'gcen', 'mcsv', 'ctasm']
other_projects_acronym = ['cbic','conv','depb','pgto','port','trnf','alcd','antv','atad','atcl','atco','atfd','atkn','clbk','herm','retr','bpmo','gedc','pvfr','pvld','aant','bimo','cess','crgr','crmd','epat','fdos','gagc','glcr','glpf','glpj','intr','inve','invo','mbio','prev','tsbo']
relevant_files = ['application.properties', 'application-hml.properties', 'application-dev.properties', 'application-prd.properties', 'bootstrap.yml']

# fernanda_valid_projects = [
#   'apio-canal-renovacao-emprestimo-java',
#   'apio-retorno-recebiveis-java',
#   'apio-canal-abertura-cadastro-java',
#   'apio-canal-pagamentos-pix-java',
#   'apio-consultas-debito-automatico-java',
#   'apio-qr-code-java',
#   'apio-solicitacao-cartao-java',
#   'apio-canal-gerador-pagamento-fatura-java',
#   'apio-canal-extratos-parceiro-java',
#   'apio-canal-cartao-pre-pago-virtual-java',
#   'apio-canal-aditamento-nao-correntista-java',
#   'apio-campanha-consentimento-java',
#   'apio-boletos-parceiro-java',
#   'apio-canal-manifestacao-lgpd-java',
#   'apio-canal-clientes-java',
#   'apio-canal-saque-digital-java',
#   'apio-canal-consultar-contratos-emprestimos-java',
#   'cdps-atualizar-contato-cadastro-java',
#   'cdps-consultar-informacoes-cliente-java',
#   'cdps-campanhas-java',
#   'cdps-servicos-cmm-java',
#   'cdps-rendas-java',
#   'cdps-atualizar-dados-empregador-java',
#   'cdps-orq-cadastro-nao-correntista-java',
#   'cdps-segmentos-java',
#   'cdps-produtos-java',
#   'cdps-bens-cadastrados-java',
#   'cdps-atualizar-dados-conjuge-java',
#   'ctas-efetivar-debito-java',
#   'ctas-sincronizacao-tabelas-java',
#   'ctas-saldo-java',
#   'ctas-orquestrador-transacoes-java',
#   'ctas-consumidor-encerramento-contas-irregulares-java',
#   'ctas-consulta-bloqueio-transacional-java',
#   'ctas-credito-imediato-java',
#   'ctas-efetivar-credito-java',
#   'ctas-extratos-java',
#   'ctas-validar-aptidao-transacao-conta-java',
#   'ctas-cmm-rest-java',
#   'ctas-status-lancamentos-efetivar-java',
#   'ctas-lancamentos-a-efetivar-java',
#   'ctas-validacoes-java',
#   'ctas-consultas-id-fisico-java',
#   'ctas-consulta-lancamentos-java',
#   'fepw-cmm-rest-java',
#   'fepw-manutencao-java',
#   'parc-dados-cadastrais-parcerias-java',
#   'rtto-consultar-contrato-cheque-especial-java',
#   'rtto-consumer-manutencao-limites-java',
#   'rtto-operacoes-java',
#   'rtto-consultar-cheque-especial-java',
#   'rtto-manutencao-limite-java',
#   'rtto-cet-java',
#   'rtto-operacoes-renegociacao-java',
#   'tbgr-eventos-java',
#   'tbgr-cartorios-java',
#   'tbgr-consultas-java',
#   'tbgr-produtos-java',
#   'tbgr-servicos-cmm-java',
#   'tbgr-bancos-java',
#   'tbgr-dominios-java',
#   'tbgr-usuario-sistema-java',
#   'tbgr-consulta-regras-java',
#   'tbgr-sincronizacao-tabelas-java',
#   'tbgr-dias-uteis-java',
#   'tbgr-canais-java',
#   'tbgr-canal-cartorios-java',
#   'trfo-cmm-rest-java',
#   'trfo-contratacao-java'
# ]
#
# fernanda_dictionary = {
#   'acad': [ project for project in fernanda_valid_projects if project.startswith('acad') ],
#   'apio': [ project for project in fernanda_valid_projects if project.startswith('apio') ],
#   'cdps': [ project for project in fernanda_valid_projects if project.startswith('cdps') ],
#   'ctas': [ project for project in fernanda_valid_projects if project.startswith('ctas') ],
#   'fepw': [ project for project in fernanda_valid_projects if project.startswith('fepw') ],
#   'parc': [ project for project in fernanda_valid_projects if project.startswith('parc') ],
#   'rtto': [ project for project in fernanda_valid_projects if project.startswith('rtto') ],
#   'tbgr': [ project for project in fernanda_valid_projects if project.startswith('tbgr') ],
#   'trfo': [ project for project in fernanda_valid_projects if project.startswith('trfo') ],
#   'atmo': [ project for project in fernanda_valid_projects if project.startswith('atmo') ],
#   'gcen': [ project for project in fernanda_valid_projects if project.startswith('gcen') ],
#   'mcsv': [ project for project in fernanda_valid_projects if project.startswith('mcsv') ],
#   'ctasm': [ project for project in fernanda_valid_projects if project.startswith('ctasm') ]
# }
#
#
